version: "3.9"  # optional since v1.27.0 # con docker host.docker.internal
services: 
  mysql:
    image: mysql:8.0.26
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3308:3306"
  
    environment:     
      MYSQL_DATABASE: 'tp-dan' 
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        
    volumes:
        - ./mysql-data:/var/lib/mysql
        - ./ESQUEMA_DAN_01.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
        - infra
        - app           
              
  adminer:
    image: adminer
    restart: always
    ports:
      - 6001:8080
    networks:
        - infra

  artemis:
    image: artemis
    restart: always
    ports:
      - "61616:61616" 
      - "8161:8161"
      - "5445:5445"
      - "5672:5672"
      - "1883:1883" 
      - "61613:61613"
    networks:
      - infra
      - app
  
networks:
    infra:
        driver: bridge
    app:
        driver: bridge
        name: dan-docker_app


